Adding ability to delete a IIIF collection
dlcs/iiif-presentation pull request #184
Opened 2024-11-22 11:20 UTC by JackLewis-digirati

2024-11-22 13:42 UTC, griffri commented on src/IIIFPresentation/API.Tests/Integration/DeleteCollectionTests.cs
> +        var response = await httpClient.AsCustomer(1).SendAsync(requestMessage);
It looks like all of these tests make requests as customer 1 - would it be worth defining a `customerId` const?

2024-11-22 13:42 UTC, griffri approved these changes

2024-11-22 13:43 UTC, donaldgray requested changes

2024-11-22 13:43 UTC, donaldgray commented on src/IIIFPresentation/API.Tests/Integration/DeleteCollectionTests.cs
> +        var initialCollection = new Collection()
There's a lot of repetition in Collection tests - could we use `DatabaseTestDataPopulation.AddTestCollection()` here (may need tweaked)? It'll keep the tests more concise to show what's useful.

2024-11-22 13:43 UTC, donaldgray commented on src/IIIFPresentation/API.Tests/Integration/DeleteCollectionTests.cs
> +    public async Task DeleteCollection_FailsToDeleteCollection_WhenAttemptingToDeleteRootDirectly()
This test looks identical to `DeleteCollection_FailsToDeleteCollection_WhenAttemptingToDeleteRoot()`

2024-11-22 13:43 UTC, donaldgray commented on src/IIIFPresentation/API/Infrastructure/AWS/IIIFS3Service.cs
> +        bucketWriter.DeleteFromBucket(item);
unawaited `Task`

2024-11-27 09:19 UTC, donaldgray approved these changes

2024-11-27 09:27 UTC, merged